language = {
    "zh-cn": {
        "title": "Neon Abyss 2 修改器",
        "wait_game": "等待启动游戏",
        "enable": "启用",
        "lock": "锁定",
        "lockMax": "锁定至最大",
        "open": "开启",
        "value": "数值：",
        "GOLD": "金币",
        "HEALTH": "血量",
        "SHIELDS": "护盾",
        "BOMBER": "手雷",
        "BOMBER_ICE": "冰霜手雷",
        "BOMBER_FIRE": "火焰手雷",
        "BOMBER_THUNDER": "雷电手雷",
        "BOMBER_DARK": "暗手雷",
        "BOMBER_POISON": "毒素手雷",
        "KEYS": "钥匙",
        "MANA": "水晶",
        "GUN_LEN": "射程",
        "GUN_SUM": "子弹列数",
        "GUN_SPEED": "射速",
        "MOVE_SPEED": "移动速度",
        "JUMP_HIGHER": "跳跃高度",
        "JUMP_SUM": "跳跃次数",
        "FIRE_LEVEL": "火焰伤害等级",
        "THUNDER_LEVEL": "闪电伤害等级",
        "POISON_LEVEL": "毒素伤害等级",
        "ICE_LEVEL": "冰霜伤害等级",
        "BLAST_LEVEL": "爆炸伤害等级",
        "MAGIC_LEVEL": "魔法伤害等级",
        "TEC_LEVEL": "科技伤害等级",
        "BUBBLE_LEVEL": "萌萌伤害等级",
        "PHYSICAL_LEVEL": "物理伤害等级",
        "SOUL_LEVEL": "暗灵伤害等级",
        "CURSE_LEVEL": "诅咒等级",
        "GOLD_SOUL_SUM": "金色暗灵数量",
        "TEMP_SOUL_SUM": "临时暗灵数量",
    },
    "en-us": {
        "title": "Neon Abyss 2 Helper",
        "wait_game": "Wait game start ...",
        "enable": "Enable",
        "lock": "Lock",
        "lockMax": "Lock to Max",
        "open": "Open",
        "value": "Value：",
        "GOLD": "Gold",
        "HEALTH": "HP",
        "SHIELDS": "Shield",
        "BOMBER": "Grenade",
        "KEYS": "Key",
        "MANA": "Crystal",
        "GUN_LEN": "Range",
        "GUN_SUM": "Bullet Columns",
        "GUN_SPEED": "Fire Rate",
        "MOVE_SPEED": "Movement Speed",
        "JUMP_HIGHER": "Jump Height",
        "JUMP_SUM": "Jump Count",
        "FIRE_LEVEL": "Fire Damage Level",
        "THUNDER_LEVEL": "Lightning Damage Level",
        "POISON_LEVEL": "Poison Damage Level",
        "ICE_LEVEL": "Frost Damage Level",
        "BLAST_LEVEL": "Explosion Damage Level",
        "MAGIC_LEVEL": "Magic Damage Level",
        "TEC_LEVEL": "Tech Damage Level",
        "BUBBLE_LEVEL": "Bubble Damage Level",
        "PHYSICAL_LEVEL": "Physical Damage Level",
        "SOUL_LEVEL": "Dark Spirit Damage Level",
        "CURSE_LEVEL": "Curse Level",
        "GOLD_SOUL_SUM": "Golden Spirit Count",
        "TEMP_SOUL_SUM": "Temporary Spirit Count",
    }
}