language = {
    "zh-cn": {
        "title": "Neon Abyss 2 修改器",
        "enable": "启用",
        "lock": "锁定",
        "lockMax": "锁定至最大",
        "open": "开启",
        "value": "数值：",
        "GOLD": "金币",
        "HEALTH": "血量",
        "SHIELDS": "护盾",
        "BOMBER": "手雷",
        "BOMBER_ICE": "冰霜手雷",
        "BOMBER_FIRE": "火焰手雷",
        "BOMBER_THUNDER": "雷电手雷",
        "BOMBER_DARK": "暗手雷",
        "BOMBER_POISON": "毒素手雷",
        "KEYS": "钥匙",
        "MANA": "水晶",
        "GUN_LEN": "射程",
        "GUN_SUM": "子弹列数",
        "GUN_SPEED": "射速",
        "GUN_BOLL": "子弹伤害",
        "GUN_LEVEL": "武器等级",
        "MOVE_SPEED": "移动速度",
        "JUMP_HIGHER": "跳跃高度",
        "JUMP_SUM_NO_MARK": "无印记跳跃次数",
        "JUMP_SUM": "跳跃次数",
        "FIRE_LEVEL": "火焰伤害等级",
        "THUNDER_LEVEL": "闪电伤害等级",
        "POISON_LEVEL": "毒素伤害等级",
        "ICE_LEVEL": "冰霜伤害等级",
        "BLAST_LEVEL": "爆炸伤害等级",
        "MAGIC_LEVEL": "魔法伤害等级",
        "TEC_LEVEL": "科技伤害等级",
        "BUBBLE_LEVEL": "萌萌伤害等级",
        "PHYSICAL_LEVEL": "物理伤害等级",
        "SOUL_LEVEL": "暗灵伤害等级",
        "CURSE_LEVEL": "诅咒等级",
        "GOLD_SOUL_SUM": "金色暗灵数量",
        "TEMP_SOUL_SUM": "临时暗灵数量",
        "DAMAGE": "受击伤害",
        "KNIFE_SPEED": "近战武器攻速",
        "TIME_OF_DAMAGE": "伤害持续时间",
        "CRIT_RATE": "暴击几率",
        "GUN_EXP_PRT": "武器升级经验百分比",
        "IS_FLY": "是否飞行",
        "IS_MACHINE_DAMAGE": "机器是否损坏",
        "BOX_WIN_PROB": "宝箱获胜概率"
    },
    "en-us": {
        "title": "Neon Abyss 2 Helper",
        "enable": "Enable",
        "lock": "Lock",
        "lockMax": "Lock to Max",
        "open": "Open",
        "value": "Value：",
        "GOLD": "Gold",
        "HEALTH": "HP",
        "SHIELDS": "Shield",
        "BOMBER": "Grenade",
        "BOMBER_ICE": "Frost Grenade",
        "BOMBER_FIRE": "Fire Grenade",
        "BOMBER_THUNDER": "Lightning Grenade",
        "BOMBER_DARK": "Dark Grenade",
        "BOMBER_POISON": "Poison Grenade",
        "KEYS": "Key",
        "MANA": "Crystal",
        "GUN_LEN": "Range",
        "GUN_SUM": "Bullet Columns",
        "GUN_SPEED": "Fire Rate",
        "GUN_BOLL": "Bullet Damage",
        "GUN_LEVEL": "Weapon Level",
        "MOVE_SPEED": "Movement Speed",
        "JUMP_HIGHER": "Jump Height",
        "JUMP_SUM_NO_MARK": "Markless Jumps",
        "JUMP_SUM": "Jump Count",
        "FIRE_LEVEL": "Fire Damage Level",
        "THUNDER_LEVEL": "Lightning Damage Level",
        "POISON_LEVEL": "Poison Damage Level",
        "ICE_LEVEL": "Frost Damage Level",
        "BLAST_LEVEL": "Explosion Damage Level",
        "MAGIC_LEVEL": "Magic Damage Level",
        "TEC_LEVEL": "Tech Damage Level",
        "BUBBLE_LEVEL": "Bubble Damage Level",
        "PHYSICAL_LEVEL": "Physical Damage Level",
        "SOUL_LEVEL": "Dark Spirit Damage Level",
        "CURSE_LEVEL": "Curse Level",
        "GOLD_SOUL_SUM": "Golden Spirit Count",
        "TEMP_SOUL_SUM": "Temporary Spirit Count",
        "DAMAGE": "Damage Taken",
        "KNIFE_SPEED": "Melee Attack Speed",
        "TIME_OF_DAMAGE": "Damage Duration",
        "CRIT_RATE": "Critical Rate",
        "GUN_EXP_PRT": "Weapon EXP Percentage",
        "IS_FLY": "Fly",
        "IS_MACHINE_DAMAGE": "Machine Broken",
        "BOX_WIN_PROB": "Chest Win Chance"
    }
}