language = {
    "zh-cn": {
        "title": "Neon Abyss 2 修改器",
        "hide": "隐藏",
        "show": "显示",
        "helper_started": "修改器已启动",
        "config_updated": "配置修改已生效",
        "about": "关于",
        "quit": "退出",
        "wait_game": "等待启动游戏",
        "enable": "启用",
        "lock": "锁定",
        "lockMax": "锁定至最大",
        "open": "开启",
        "value": "数值：",
        "GOLD": "金币",
        "HEALTH": "血量",
        "SHIELDS": "护盾",
        "BOMBER": "手雷",
        "KEYS": "钥匙",
        "MANA": "水晶",
        "GUN_SPEED": "射速",
    },
    "en-us": {
        "title": "Neon Abyss 2 Helper",
        "hide": "Hide",
        "show": "Show",
        "helper_started": "Helper started",
        "config_updated": "Config is updated",
        "about": "About",
        "quit": "Quit",
        "wait_game": "Wait game start ...",
        "enable": "Enable",
        "lock": "Lock",
        "lockMax": "Lock to Max",
        "open": "Open",
        "value": "Value：",
        "GOLD": "Gold",
        "HEALTH": "HP",
        "SHIELDS": "Shield",
        "BOMBER": "Grenade",
        "KEYS": "Key",
        "MANA": "Crystal",
        "GUN_SPEED": "Fire Rate",
    }
}